# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mini_skills' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mini_skills
  pod 'XLPagerTabStrip', '~> 9.0' #Scroll Offset 0...
  
  pod 'MXSegmentedPager'

end
