# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'presento' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for presento
  pod 'CarLensCollectionViewLayout', '~> 1.2.0'
  pod 'ConfettiView-NSHipster'
end
